### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by rmoff** [RedHatInsights/expandjsonsmt#12]
Using version 0.0.7 I get: 

```
Caused by: java.lang.NullPointerException                                                                                                                                                        at com.redhat.insights.expandjsonsmt.ExpandJSON.makeUpdatedSchema(ExpandJSON.java:193)
        at com.redhat.insights.expandjsonsmt.ExpandJSON.makeUpdatedSchema(ExpandJSON.java:199)
        at com.redhat.insights.expandjsonsmt.ExpandJSON.applyWithSchema(ExpandJSON.java:91)                                                                                                      at com.redhat.insights.expandjsonsmt.ExpandJSON.apply(ExpandJSON.java:75)
        at com.redhat.insights.expandjsonsmt.ExpandJSON$Value.apply(ExpandJSON.java:222)
```

with config

```
    "transforms"                        : "expand",
    "transforms.expand.type"            : "com.redhat.insights.expandjsonsmt.ExpandJSON$Value",
    "transforms.expand.sourceFields"    : "text"
```

and source message (using `org.apache.kafka.connect.json.JsonConverter`)

```json
{"messageID":"ID:opendata-backend.rockshore.net-38745-1609843645734-11:1:1:19:5119","messageType":"text","timestamp":1609968054024,"deliveryMode":2,"correlationID":null,"replyTo":null,"destination":{"destinationType":"topic","name":"TRAIN_MVT_EA_TOC"},"redelivered":false,"type":null,"expiration":1609968354024,"priority":4,"properties":{},"bytes":null,"map":null,"text":"[{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1609968045000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"ARRIVAL\",\"gbtt_timestamp\":\"1609967700000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1609967700000\",\"timetable_variation\":\"7\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"\",\"reporting_stanox\":\"12931\",\"actual_timestamp\":\"1609968120000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\" 3\",\"division_code\":\"20\",\"train_terminated\":\"true\",\"train_id\":\"361P37MV06\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"21734000\",\"toc_id\":\"20\",\"loc_stanox\":\"12931\",\"auto_expected\":\"true\",\"direction_ind\":\"DOWN\",\"route\":\"0\",\"planned_event_type\":\"DESTINATION\",\"next_report_stanox\":\"\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1609968046000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"DEPARTURE\",\"gbtt_timestamp\":\"\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1609968000000\",\"timetable_variation\":\"0\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"false\",\"next_report_run_time\":\"\",\"reporting_stanox\":\"00000\",\"actual_timestamp\":\"1609968000000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\"\",\"division_code\":\"20\",\"train_terminated\":\"false\",\"train_id\":\"191K34MZ06\",\"offroute_ind\":\"false\",\"variation_status\":\"ON TIME\",\"train_service_code\":\"21733000\",\"toc_id\":\"20\",\"loc_stanox\":\"18440\",\"auto_expected\":\"true\",\"direction_ind\":\"UP\",\"route\":\"2\",\"planned_event_type\":\"DEPARTURE\",\"next_report_stanox\":\"18442\",\"line_ind\":\"F\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1609968053000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"DEPARTURE\",\"gbtt_timestamp\":\"1609967820000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1609967850000\",\"timetable_variation\":\"2\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"false\",\"next_report_run_time\":\"4\",\"reporting_stanox\":\"00000\",\"actual_timestamp\":\"1609967940000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\" 2\",\"division_code\":\"20\",\"train_terminated\":\"false\",\"train_id\":\"172J80MZ06\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"21733000\",\"toc_id\":\"20\",\"loc_stanox\":\"18472\",\"auto_expected\":\"true\",\"direction_ind\":\"UP\",\"route\":\"1\",\"planned_event_type\":\"DEPARTURE\",\"next_report_stanox\":\"18474\",\"line_ind\":\"M\"}}]"}
```

Does this Single Message Transform rely on a Schema being present?

**Comment by rmoff** [comment]
@Josca any suggestions on how to resolve this error? Thanks :)

**Comment by Josca** [comment]
@maorfr It seems the source field is missing in your input data. Maybe only in one row.

**Comment by rmoff** [comment]
Ah, that might make sense, given the data. Do you think condition could be handled by the SMT?

**Comment by Josca** [comment]
@rmoff definitelly could be. But someone would have to implement that :smile: . Feel free to create PR! Maybe we could add `defaultValue` for that case?

**Comment by rmoff** [comment]
> Feel free to create PR!

😁  I would love to but I'm not a Java coder. Shall we leave this issue open for now for others to help with if they can?

**Comment by Josca** [comment]
@rmoff sure, keep it open if you want

**Comment by rmoff** [comment]
I'm just revisiting this now. Looking at the connect Record, I noticed that the field I'm interested in is a JSON array: 

```
text=[{"header":{"msg_type":"0003","source_dev_id":"","user_id":"","original_data_source":"SMART","msg_queue_timestamp":"1616084988000","source_system_id":"TRUST"},"body":{"event_type":"DEPARTURE","gbtt_timestamp":"","original_loc_stanox":"","planned_timestamp":"1616084910000","timetable_variation":"1","original_loc_timestamp":"","current_train_id":"","delay_monitoring_point":"true","next_report_run_time":"4","reporting_stanox":"16495","actual_timestamp":"1616084940000","correction_ind":"false","event_source":"AUTOMATIC","train_file_address":null,"platform":"","division_code":"20","train_terminated":"false","train_id":"151K781Q18","offroute_ind":"false","variation_status":"LATE","train_service_code":"21734000","toc_id":"20","loc_stanox":"16495","auto_expected":"true","direction_ind":"UP","route":"2","planned_event_type":"DEPARTURE","next_report_stanox":"16602","line_ind":"L"}},{"header":{"msg_type":"0003","source_dev_id":"","user_id":"","original_data_source":"SMART","msg_queue_timestamp":"1616084988000","source_system_id":"TRUST"},"body":{"event_type":"ARRIVAL","gbtt_timestamp":"","original_loc_stanox":"","planned_timestamp":"","timetable_variation":"0","original_loc_timestamp":"","current_train_id":"","delay_monitoring_point":"false","next_report_run_time":"","reporting_stanox":"","actual_timestamp":"1616085000000","correction_ind":"false","event_source":"AUTOMATIC","train_file_address":null,"platform":"","division_code":"20","train_terminated":"false","train_id":"129M301P18","offroute_ind":"true","variation_status":"OFF ROUTE","train_service_code":"21731000","toc_id":"20","loc_stanox":"18441","auto_expected":"","direction_ind":"","route":"","planned_event_type":"ARRIVAL","next_report_stanox":"","line_ind":""}}]
```

So could the NPE seen above be caused by that?
